### ISSUE TITLE
Custom scripts

### ISSUE THREAD

**Issue by kristian240** [infinum/js-pipeline#21]
Right now `build`, `lint`, `test`, ... commands are running corresponding `npm` scripts. However, it might be useful if we can add a possibility to override a specific command with a custom one.

## Scenario
I want to have two scripts for testing - one that I use for development and one that is being used on CI.

## Current
I have 2 scripts - `test` for CI and `test:coverage` for dev. The DX is not great since I need to adapt my workflow because we do not want to trigger a test run with `coverage` on our app to improve the speed. So now, everytime I want to run the tests locally and I want to checkout the coverage I need to run `npm run test:coverage` or `yarn test:coverage`.

## Workaround
I could check which environment I'm using and then make 3 scripts - `test`, `test:ci` and `test:coverage`. Then the `test` script would be basically `ifCi ? testCi() : testCoverage()`. Then I can run `npm run test` both on ci and local and the DX is improved.

## Solution
If we allow the custom scripts to be passed in to actions then this problem could be solved once in much easier way. Two scripts - `test` for dev and `test:ci` for CI. 

## API

```yml
jobs:
  test-analyze:
    name: 'Run'
    uses: infinum/js-pipeline/.github/workflows/pipeline.yml@v2
    with:
      ci_steps: 'lint test analyze'
      workflow: '.github/workflows/pr.yml'
      test: npm run test:ci # custom test command
      build: npm run build:ci # custom build command
```

Maybe the entire issue is just nitpicking but I can see how this can solve potential issues in the future.

If you think this is a good idea, I would love to implement the changes myself :D
